# Generated by Django 2.2.13 on 2022-03-11 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220311_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecolumn',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articlecolumn',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
